/**
 * copilot-prompts.js
 * All 20 QA Lab Copilot prompt templates.
 * Keyed by page filename (e.g. "01-simple-login.html").
 */

window.QALabPrompts = {

'01-simple-login.html': {
  title: 'Simple Login Form',
  difficulty: 'Beginner',
  url: 'pages/01-simple-login.html',
  description: 'A login form with username and password fields, submit/cancel buttons, inline validation, password visibility toggle, and a DOM-swap success state.',
  elements: [
    { testid: 'login-form',        type: 'form',     desc: 'The login form element' },
    { testid: 'input-username',    type: 'input',    desc: 'Username text input' },
    { testid: 'input-password',    type: 'input',    desc: 'Password input (type toggles text/password)' },
    { testid: 'toggle-password',   type: 'button',   desc: 'Show/hide password toggle button' },
    { testid: 'checkbox-remember', type: 'checkbox', desc: 'Remember me checkbox' },
    { testid: 'btn-submit',        type: 'button',   desc: 'Submit the login form' },
    { testid: 'btn-cancel',        type: 'button',   desc: 'Reset and clear the form' },
    { testid: 'login-alert',       type: 'div',      desc: 'Error alert box (display:none when hidden)' },
    { testid: 'error-username',    type: 'div',      desc: 'Inline username validation error' },
    { testid: 'error-password',    type: 'div',      desc: 'Inline password validation error' },
    { testid: 'login-success',     type: 'div',      desc: 'Success state (replaces form on login)' },
    { testid: 'success-username',  type: 'span',     desc: 'Displays the logged-in username' },
    { testid: 'btn-logout',        type: 'button',   desc: 'Logs out and restores the login form' },
    { testid: 'link-register',     type: 'a',        desc: 'Link to registration page' },
  ],
  credentials: [
    { user: 'admin',       pass: 'admin123' },
    { user: 'tester',      pass: 'Test@2024' },
    { user: 'qa.engineer', pass: 'QA_pass!' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Successful Login', steps: ['Navigate to the page','Fill input-username with "admin"','Fill input-password with "admin123"','Click btn-submit','Assert login-success is visible','Assert success-username text is "admin"'] },
    { id: 'TC-02', name: 'Empty Form Submission', steps: ['Leave all fields empty','Click btn-submit','Assert error-username is visible and contains "required"','Assert error-password is visible and contains "required"','Assert login-form is still visible (no navigation)'] },
    { id: 'TC-03', name: 'Wrong Credentials', steps: ['Fill input-username with "admin"','Fill input-password with "wrongpassword"','Click btn-submit','Assert login-alert is visible','Assert login-alert text contains "Invalid"','Assert password field is cleared'] },
    { id: 'TC-04', name: 'Password Visibility Toggle', steps: ['Type any text in input-password','Assert attribute type is "password"','Click toggle-password','Assert attribute type is "text"','Click toggle-password again','Assert attribute type is "password"'] },
    { id: 'TC-05', name: 'Cancel Button Reset', steps: ['Fill username and password','Click btn-cancel','Assert input-username value is empty','Assert input-password value is empty','Assert login-alert is not visible'] },
    { id: 'TC-06', name: 'Logout Flow', steps: ['Login with valid credentials','Assert login-success is visible','Click btn-logout','Assert login-form is visible again','Assert login-success is hidden'] },
  ],
  pitfalls: ['No page navigation on success — DOM swaps between div#login-card and div#login-success','login-alert uses display:none not class-based hiding','Password type attribute changes dynamically — re-query field after toggle','Cancel does NOT submit — assert no success state appears']
},

'02-registration-form.html': {
  title: 'Registration Form',
  difficulty: 'Beginner',
  url: 'pages/02-registration-form.html',
  description: 'Multi-field signup form with email/phone regex, password strength meter, confirmation match, country select, terms checkbox, and inline errors per field.',
  elements: [
    { testid: 'input-first-name',       type: 'input',    desc: 'First name text field' },
    { testid: 'input-last-name',        type: 'input',    desc: 'Last name text field' },
    { testid: 'input-email',            type: 'input',    desc: 'Email address field' },
    { testid: 'input-phone',            type: 'input',    desc: 'Phone number (optional)' },
    { testid: 'input-username',         type: 'input',    desc: 'Username (3-20 chars, alphanumeric/underscore)' },
    { testid: 'input-password',         type: 'input',    desc: 'Password with strength meter' },
    { testid: 'password-strength-label',type: 'span',     desc: 'Strength label: Very Weak / Weak / Fair / Strong / Very Strong' },
    { testid: 'input-confirm-password', type: 'input',    desc: 'Password confirmation field' },
    { testid: 'select-country',         type: 'select',   desc: 'Country dropdown' },
    { testid: 'checkbox-terms',         type: 'checkbox', desc: 'Terms and conditions acceptance' },
    { testid: 'checkbox-newsletter',    type: 'checkbox', desc: 'Optional newsletter opt-in' },
    { testid: 'btn-submit',             type: 'button',   desc: 'Submit registration form' },
    { testid: 'btn-reset',              type: 'button',   desc: 'Reset form to initial state' },
    { testid: 'reg-success',            type: 'div',      desc: 'Success state shown after registration' },
    { testid: 'reg-success-name',       type: 'strong',   desc: 'Displays registered username' },
    { testid: 'error-email',            type: 'div',      desc: 'Inline email validation error' },
    { testid: 'error-confirm-password', type: 'div',      desc: 'Inline confirm password error' },
    { testid: 'error-terms',            type: 'div',      desc: 'Inline terms checkbox error' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Successful Registration', steps: ['Fill all required fields with valid data','Select a country','Check checkbox-terms','Click btn-submit','Assert reg-success is visible','Assert reg-success-name shows the username'] },
    { id: 'TC-02', name: 'Password Mismatch', steps: ['Fill required fields','Type "Password1!" in input-password','Type "Different1!" in input-confirm-password','Click btn-submit','Assert error-confirm-password is visible and contains "match"'] },
    { id: 'TC-03', name: 'Password Strength Meter', steps: ['Type "abc" — assert strength label is "Very Weak" or "Weak"','Type "Password1!" — assert label is "Strong" or "Very Strong"'] },
    { id: 'TC-04', name: 'Terms Not Accepted', steps: ['Fill all fields correctly','Leave checkbox-terms unchecked','Click btn-submit','Assert error-terms is visible','Assert form is still showing'] },
    { id: 'TC-05', name: 'Invalid Email Format', steps: ['Type "notanemail" in input-email','Click btn-submit','Assert error-email is visible and contains "valid"'] },
  ],
  pitfalls: ['Phone field is OPTIONAL — empty value must not trigger an error','Password strength updates on every keypress — assert AFTER full word is typed','Reset button clears form but does NOT navigate away']
},

'03-checkboxes-radios.html': {
  title: 'Checkboxes and Radio Buttons',
  difficulty: 'Beginner',
  url: 'pages/03-checkboxes-radios.html',
  description: 'Single checkboxes, grouped checkboxes with a select-all + indeterminate state, radio groups with pre-selection and disabled options, and CSS toggle switches.',
  elements: [
    { testid: 'cb-terms',              type: 'checkbox', desc: 'Single terms checkbox' },
    { testid: 'cb-newsletter',         type: 'checkbox', desc: 'Newsletter checkbox (pre-checked by default)' },
    { testid: 'cb-disabled',           type: 'checkbox', desc: 'Disabled checkbox (not interactable)' },
    { testid: 'btn-read-checkboxes',   type: 'button',   desc: 'Reads state of single checkboxes' },
    { testid: 'single-cb-output',      type: 'div',      desc: 'Output text for checkbox state' },
    { testid: 'cb-select-all',         type: 'checkbox', desc: 'Master select-all checkbox (has indeterminate state)' },
    { testid: 'cb-item-1',             type: 'checkbox', desc: 'Group item: Playwright' },
    { testid: 'cb-item-2',             type: 'checkbox', desc: 'Group item: Selenium' },
    { testid: 'cb-item-3',             type: 'checkbox', desc: 'Group item: Cypress' },
    { testid: 'cb-item-4',             type: 'checkbox', desc: 'Group item: WebdriverIO' },
    { testid: 'cb-item-5',             type: 'checkbox', desc: 'Group item: Robot Framework' },
    { testid: 'selection-count',       type: 'span',     desc: 'Text showing "X of 5 selected"' },
    { testid: 'selected-list',         type: 'span',     desc: 'Comma-separated list of selected values' },
    { testid: 'radio-junior',          type: 'radio',    desc: 'Junior level radio' },
    { testid: 'radio-mid',             type: 'radio',    desc: 'Mid level radio (pre-selected)' },
    { testid: 'radio-senior',          type: 'radio',    desc: 'Senior level radio' },
    { testid: 'radio-disabled',        type: 'radio',    desc: 'Disabled radio option' },
    { testid: 'radio-framework-playwright', type: 'radio', desc: 'Playwright framework radio' },
    { testid: 'toggle-dark-input',     type: 'checkbox', desc: 'Dark mode toggle switch (role=switch)' },
    { testid: 'toggle-notif-input',    type: 'checkbox', desc: 'Notifications toggle (pre-checked, role=switch)' },
    { testid: 'toggle-2fa-input',      type: 'checkbox', desc: '2FA toggle (disabled)' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Select All Checkboxes', steps: ['Assert selection-count is "0 of 5 selected"','Click cb-select-all','Assert all cb-item-N are checked','Assert selection-count is "5 of 5 selected"'] },
    { id: 'TC-02', name: 'Indeterminate State', steps: ['Click cb-select-all to select all','Click cb-item-2 to deselect it','Assert cb-select-all has indeterminate=true (JS property)','Assert selection-count is "4 of 5 selected"'] },
    { id: 'TC-03', name: 'Radio Mutual Exclusion', steps: ['Assert radio-mid is checked','Click radio-junior','Assert radio-junior is checked','Assert radio-mid is NOT checked','Assert radio-senior is NOT checked'] },
    { id: 'TC-04', name: 'Toggle Switch', steps: ['Assert toggle-dark-input is unchecked','Assert aria-checked attribute is "false"','Click toggle-dark-input','Assert toggle-dark-input is checked','Assert aria-checked attribute is "true"'] },
  ],
  pitfalls: ['Indeterminate is a JavaScript property, not an HTML attribute — use evaluate(el => el.indeterminate)','cb-newsletter is pre-checked by default — tests must account for this initial state','toggle-2fa-input is disabled — verify before trying to interact']
},

'04-dropdowns-selects.html': {
  title: 'Dropdowns and Selects',
  difficulty: 'Beginner',
  url: 'pages/04-dropdowns-selects.html',
  description: 'Native HTML selects (single, disabled), optgroup-grouped select, multi-select, and a fully custom ARIA-compliant dropdown widget built without a framework.',
  elements: [
    { testid: 'select-country',            type: 'select', desc: 'Native country single-select' },
    { testid: 'select-priority',           type: 'select', desc: 'Priority select (default: "low")' },
    { testid: 'select-disabled',           type: 'select', desc: 'Disabled select — not interactable' },
    { testid: 'btn-read-selects',          type: 'button', desc: 'Read values of native selects' },
    { testid: 'select-output',             type: 'div',    desc: 'Output showing selected values' },
    { testid: 'select-framework',          type: 'select', desc: 'Grouped framework select with optgroups' },
    { testid: 'select-skills',             type: 'select', desc: 'Multi-select (hold Ctrl to select multiple)' },
    { testid: 'btn-read-multi',            type: 'button', desc: 'Read multi-select selections' },
    { testid: 'multi-output',              type: 'div',    desc: 'Output for multi-select values' },
    { testid: 'custom-dropdown',           type: 'div',    desc: 'The custom dropdown container' },
    { testid: 'custom-dropdown-trigger',   type: 'button', desc: 'Opens/closes the custom dropdown (aria-expanded)' },
    { testid: 'custom-dropdown-list',      type: 'ul',     desc: 'The dropdown options list (role=listbox)' },
    { testid: 'custom-dropdown-value',     type: 'span',   desc: 'Displays the currently selected label' },
    { testid: 'custom-dropdown-hidden',    type: 'input',  desc: 'Hidden input holding selected value' },
    { testid: 'dd-option-python',          type: 'li',     desc: 'Python option in custom dropdown' },
    { testid: 'dd-option-javascript',      type: 'li',     desc: 'JavaScript option' },
    { testid: 'dd-option-typescript',      type: 'li',     desc: 'TypeScript option' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Native Single-Select', steps: ['Assert select-country default selected option is empty','Select option "pt" (Portugal)','Assert selected value is "pt"','Click btn-read-selects','Assert select-output contains "pt"'] },
    { id: 'TC-02', name: 'Multi-Select', steps: ['Select ["js","ts"] from select-skills','Click btn-read-multi','Assert multi-output contains "javascript" and "typescript"'] },
    { id: 'TC-03', name: 'Custom Dropdown Open and Select', steps: ['Assert custom-dropdown-list is NOT visible','Assert custom-dropdown-trigger has aria-expanded="false"','Click custom-dropdown-trigger','Assert custom-dropdown-list is visible','Assert custom-dropdown-trigger has aria-expanded="true"','Click dd-option-python','Assert custom-dropdown-list is hidden','Assert custom-dropdown-value text is "Python"','Assert custom-dropdown-hidden input value is "python"'] },
    { id: 'TC-04', name: 'Custom Dropdown Keyboard Close', steps: ['Click custom-dropdown-trigger to open','Press Escape key','Assert custom-dropdown-list is hidden'] },
  ],
  pitfalls: ['DO NOT use selectOption() on the custom dropdown — it is NOT a native select element','Read custom dropdown value from the hidden input field, not the visible label','Multi-select: Playwright selectOption() accepts an array of values directly']
},

'05-static-content.html': {
  title: 'Static Content Verification',
  difficulty: 'Beginner',
  url: 'pages/05-static-content.html',
  description: 'Pure content assertion practice: headings, stat cards, paragraphs, blockquote, navigation links, images (one intentionally broken), and a data table.',
  elements: [
    { testid: 'main-heading',         type: 'h1',   desc: 'Page main heading' },
    { testid: 'page-description',     type: 'p',    desc: 'Page subtitle paragraph' },
    { testid: 'stats-section',        type: 'section', desc: 'Statistics cards section' },
    { testid: 'stat-tests-value',     type: 'div',  desc: 'Stat card showing "1,248" total tests' },
    { testid: 'stat-passed-value',    type: 'div',  desc: 'Stat card showing "1,199" passed' },
    { testid: 'stat-failed-value',    type: 'div',  desc: 'Stat card showing "49" failed' },
    { testid: 'stat-coverage-value',  type: 'div',  desc: 'Stat card showing "94.2%" coverage' },
    { testid: 'para-intro',           type: 'p',    desc: 'Contains text "20 progressive scenarios"' },
    { testid: 'blockquote-1',         type: 'blockquote', desc: 'Quote element' },
    { testid: 'quote-author',         type: 'cite', desc: 'Author attribution inside blockquote' },
    { testid: 'link-to-login',        type: 'a',    desc: 'Internal link to login scenario' },
    { testid: 'link-external',        type: 'a',    desc: 'External link with target="_blank"' },
    { testid: 'link-disabled',        type: 'a',    desc: 'Link with aria-disabled="true"' },
    { testid: 'img-logo',             type: 'img',  desc: 'Logo image (visible, has alt text)' },
    { testid: 'img-broken',           type: 'img',  desc: 'Intentionally broken image — src does not exist' },
    { testid: 'static-table',         type: 'table', desc: 'Data table with 5 framework rows' },
    { testid: 'static-table-body',    type: 'tbody', desc: 'Table body — assert row count' },
    { testid: 'row-playwright',       type: 'tr',   desc: 'First table row — Playwright' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Heading Text Assertions', steps: ['Assert main-heading text is "Static Content Verification"','Assert para-intro contains "20 progressive scenarios"','Assert blockquote-1 is visible','Assert quote-author text contains "QA Lab Team"'] },
    { id: 'TC-02', name: 'Stat Card Values', steps: ['Assert stat-tests-value text is "1,248"','Assert stat-passed-value text is "1,199"','Assert stat-failed-value text is "49"','Assert stat-coverage-value text is "94.2%"'] },
    { id: 'TC-03', name: 'Link Attribute Assertions', steps: ['Assert link-external has attribute target="_blank"','Assert link-external has attribute rel containing "noopener"','Assert link-disabled has aria-disabled="true"','Assert link-to-login href contains "01-simple-login.html"'] },
    { id: 'TC-04', name: 'Table Row Count', steps: ['Assert static-table-body has exactly 5 rows','Assert first row cell text contains "Playwright"','Assert row-playwright badge has class "badge-beginner"'] },
  ],
  pitfalls: ['Broken image is in the DOM and visible (broken icon) — element still exists','Numbers in stat cards contain commas: use toContainText not exact match carefully','The disabled link uses aria-disabled not the disabled attribute — pointer-events:none via CSS']
},

'06-dynamic-table.html': {
  title: 'Dynamic Table',
  difficulty: 'Intermediate',
  url: 'pages/06-dynamic-table.html',
  description: 'A fully client-side table with 20 users, sortable columns (aria-sort), client-side pagination, live search filter, row checkbox selection, and delete functionality.',
  elements: [
    { testid: 'data-table',         type: 'table',    desc: 'The main data table' },
    { testid: 'table-search',       type: 'input',    desc: 'Live search input (debounced 200ms)' },
    { testid: 'table-page-size',    type: 'select',   desc: 'Rows per page (5/10/25)' },
    { testid: 'table-info',         type: 'span',     desc: 'Text showing "Showing X of Y users"' },
    { testid: 'th-name',            type: 'th',       desc: 'Name column header — sortable, has aria-sort' },
    { testid: 'th-role',            type: 'th',       desc: 'Role column header — sortable' },
    { testid: 'th-status',          type: 'th',       desc: 'Status column header — sortable' },
    { testid: 'th-date',            type: 'th',       desc: 'Joined date column header — sortable' },
    { testid: 'select-all-rows',    type: 'checkbox', desc: 'Master select-all checkbox (has indeterminate state)' },
    { testid: 'btn-delete-selected',type: 'button',   desc: 'Delete selected rows (disabled when none selected)' },
    { testid: 'btn-add-row',        type: 'button',   desc: 'Add a new row to the table' },
    { testid: 'data-table-body',    type: 'tbody',    desc: 'Table body — rows rendered by JS' },
    { testid: 'table-empty',        type: 'div',      desc: 'Empty state shown when no search results' },
    { testid: 'pagination-container', type: 'div',   desc: 'Pagination controls' },
    { testid: 'page-next',          type: 'button',   desc: 'Go to next page' },
    { testid: 'page-prev',          type: 'button',   desc: 'Go to previous page' },
    { testid: 'page-btn-1',         type: 'button',   desc: 'Page 1 button (aria-current="page")' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Sort by Name Ascending', steps: ['Assert table has 10 rows (default page size)','Click th-name column header','Assert th-name aria-sort is "ascending"','Assert first row name is alphabetically before last row name','Click th-name again','Assert th-sort is "descending"'] },
    { id: 'TC-02', name: 'Search Filter', steps: ['Type "admin" in table-search','Wait 400ms for debounce','Assert only rows where name/role/email contains "admin" are visible','Assert table-info shows filtered count','Clear search input','Assert all rows return'] },
    { id: 'TC-03', name: 'Pagination', steps: ['Assert page-btn-1 has aria-current="page"','Click page-next','Assert page-btn-2 (or similar) has aria-current="page"','Assert different rows are displayed'] },
    { id: 'TC-04', name: 'Row Selection and Delete', steps: ['Click checkbox on row with data-row-id="1"','Assert btn-delete-selected is enabled','Click checkbox on row with data-row-id="2"','Click btn-delete-selected','Accept browser confirm dialog','Assert those 2 rows are no longer in the table','Assert table-info count decreased'] },
  ],
  pitfalls: ['Delete triggers a native browser confirm() dialog — handle with dialog event or page.on("dialog")','Row DOM indices change after sort/filter — use data-row-id not row position','Pagination re-renders all rows — re-query locators after page change','Search debounce is 200ms — assert after waiting']
},

'07-modals-toasts.html': {
  title: 'Modals and Toast Notifications',
  difficulty: 'Intermediate',
  url: 'pages/07-modals-toasts.html',
  description: 'Modal dialogs (info, confirm, scrollable, form-inside-modal) with backdrop click and Escape key close. Toast notifications in 4 types with 4s auto-dismiss and persistent option.',
  elements: [
    { testid: 'btn-toast-success',     type: 'button', desc: 'Trigger success toast' },
    { testid: 'btn-toast-error',       type: 'button', desc: 'Trigger error toast' },
    { testid: 'btn-toast-warning',     type: 'button', desc: 'Trigger warning toast' },
    { testid: 'btn-toast-info',        type: 'button', desc: 'Trigger info toast' },
    { testid: 'btn-toast-persistent',  type: 'button', desc: 'Trigger persistent toast (no auto-dismiss)' },
    { testid: 'btn-open-info-modal',   type: 'button', desc: 'Opens the info modal' },
    { testid: 'modal-info',            type: 'div',    desc: 'Info modal backdrop (hidden class = closed)' },
    { testid: 'btn-close-info-modal',  type: 'button', desc: 'Close button inside info modal' },
    { testid: 'btn-modal-info-ok',     type: 'button', desc: 'OK button in modal footer' },
    { testid: 'btn-open-confirm-modal',type: 'button', desc: 'Opens the confirm modal' },
    { testid: 'modal-confirm',         type: 'div',    desc: 'Confirm modal backdrop' },
    { testid: 'btn-modal-confirm-yes', type: 'button', desc: 'Confirm YES button' },
    { testid: 'btn-modal-confirm-no',  type: 'button', desc: 'Confirm NO button' },
    { testid: 'confirm-result',        type: 'div',    desc: 'Shows confirmation outcome after modal closes' },
    { testid: 'btn-open-form-modal',   type: 'button', desc: 'Opens modal with a form inside' },
    { testid: 'modal-form',            type: 'div',    desc: 'Form modal backdrop' },
    { testid: 'input-task-title',      type: 'input',  desc: 'Task title input inside modal' },
    { testid: 'select-task-priority',  type: 'select', desc: 'Priority dropdown inside modal' },
    { testid: 'btn-task-submit',       type: 'button', desc: 'Submit button inside form modal' },
    { testid: 'form-modal-result',     type: 'div',    desc: 'Success message after form modal submit' },
    { testid: 'toast-success',         type: 'div',    desc: 'Success toast element (in toast-container)' },
    { testid: 'toast-close',           type: 'button', desc: 'Close button inside any toast' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Open and Close Info Modal', steps: ['Assert modal-info has class "hidden"','Click btn-open-info-modal','Assert modal-info does NOT have class "hidden"','Assert modal title text is "Information"','Click btn-close-info-modal','Assert modal-info has class "hidden" again'] },
    { id: 'TC-02', name: 'Modal Close via Backdrop', steps: ['Open modal-info','Click the modal backdrop (outside the modal box)','Assert modal-info is hidden'] },
    { id: 'TC-03', name: 'Modal Close via Escape', steps: ['Open modal-info','Press Escape key','Assert modal-info is hidden'] },
    { id: 'TC-04', name: 'Confirm Modal Yes', steps: ['Click btn-open-confirm-modal','Click btn-modal-confirm-yes','Assert modal is closed','Assert confirm-result is visible','Assert confirm-result contains "confirmed"'] },
    { id: 'TC-05', name: 'Toast Auto Dismiss', steps: ['Click btn-toast-success','Assert toast with data-testid "toast-success" is visible','Wait 5 seconds','Assert toast element is no longer in the DOM'] },
    { id: 'TC-06', name: 'Form Inside Modal', steps: ['Click btn-open-form-modal','Fill input-task-title with "My Task"','Select "high" from select-task-priority','Click btn-task-submit','Assert modal-form is hidden','Assert form-modal-result is visible and contains "My Task"'] },
  ],
  pitfalls: ['Modals use class "hidden" not display:none — check for class, not visibility style','Body overflow is set to hidden when a modal is open','Persistent toast requires manual close — no auto-dismiss timer','Focus moves inside modal on open — assert focused element is the first button']
},

'08-tabs-accordions.html': {
  title: 'Tabs and Accordions',
  difficulty: 'Intermediate',
  url: 'pages/08-tabs-accordions.html',
  description: 'Full ARIA-compliant tab set with Arrow key navigation and hidden panels. Two accordion types: exclusive (one at a time) and multi-open.',
  elements: [
    { testid: 'tabs-nav-1',          type: 'div',    desc: 'Tab list container (role=tablist)' },
    { testid: 'tab-playwright',      type: 'button', desc: 'Playwright tab (role=tab, default selected)' },
    { testid: 'tab-selenium',        type: 'button', desc: 'Selenium tab' },
    { testid: 'tab-cypress',         type: 'button', desc: 'Cypress tab' },
    { testid: 'tab-robot',           type: 'button', desc: 'Robot Framework tab' },
    { testid: 'tabpanel-playwright', type: 'div',    desc: 'Playwright panel (role=tabpanel, default visible)' },
    { testid: 'tabpanel-selenium',   type: 'div',    desc: 'Selenium panel (hidden by default)' },
    { testid: 'tabpanel-cypress',    type: 'div',    desc: 'Cypress panel (hidden by default)' },
    { testid: 'accordion-header-1',  type: 'button', desc: 'Accordion header 1 (exclusive type)' },
    { testid: 'accordion-header-2',  type: 'button', desc: 'Accordion header 2 (exclusive type)' },
    { testid: 'accordion-header-3',  type: 'button', desc: 'Accordion header 3 (exclusive type)' },
    { testid: 'accordion-body-1',    type: 'div',    desc: 'Accordion body 1' },
    { testid: 'accordion-item-1',    type: 'div',    desc: 'Accordion item 1 container (has class "open" when expanded)' },
    { testid: 'accordion-m-header-1',type: 'button', desc: 'Multi-open accordion header 1 (pre-opened)' },
    { testid: 'accordion-m-header-2',type: 'button', desc: 'Multi-open accordion header 2' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Tab Navigation Click', steps: ['Assert tab-playwright has aria-selected="true" and class "active"','Assert tabpanel-playwright is visible (not hidden)','Assert tabpanel-selenium has HTML hidden attribute','Click tab-selenium','Assert tab-selenium aria-selected is "true"','Assert tabpanel-selenium is visible','Assert tabpanel-playwright is hidden'] },
    { id: 'TC-02', name: 'Tab Keyboard Navigation', steps: ['Focus on tab-playwright','Press ArrowRight key','Assert tab-selenium receives focus and becomes active','Press ArrowRight again','Assert tab-cypress is active'] },
    { id: 'TC-03', name: 'Exclusive Accordion', steps: ['Assert all accordion items have no class "open"','Click accordion-header-1','Assert accordion-item-1 has class "open"','Assert accordion-header-1 aria-expanded is "true"','Click accordion-header-2','Assert accordion-item-2 has class "open"','Assert accordion-item-1 does NOT have class "open" (auto-closed)'] },
    { id: 'TC-04', name: 'Multi-Open Accordion', steps: ['Assert accordion-m-item-1 has class "open" (pre-opened)','Click accordion-m-header-2','Assert accordion-m-item-2 has class "open"','Assert accordion-m-item-1 STILL has class "open" (both open simultaneously)'] },
  ],
  pitfalls: ['Tab panels use HTML hidden attribute — use toBeHidden() or check for hidden attribute, not display style','Accordion body height is CSS max-height animated — assert text visibility not height value','Arrow key navigation requires the tab button to have focus first']
},

'09-form-validation.html': {
  title: 'Advanced Form Validation',
  difficulty: 'Intermediate',
  url: 'pages/09-form-validation.html',
  description: 'Real time regex validation, password strength rules checklist, debounced async username availability check (600ms debounce + 1200ms fake API), conditional business fields reveal.',
  elements: [
    { testid: 'input-username',         type: 'input',  desc: 'Username with debounced async availability check' },
    { testid: 'username-check-icon',    type: 'span',   desc: 'Shows check icon after async check' },
    { testid: 'username-checking',      type: 'div',    desc: 'Shown while async check is in progress' },
    { testid: 'username-available',     type: 'div',    desc: 'Shown when username is available' },
    { testid: 'username-taken',         type: 'div',    desc: 'Shown when username is taken' },
    { testid: 'input-email',            type: 'input',  desc: 'Email with real time validation' },
    { testid: 'input-password',         type: 'input',  desc: 'Password with strength meter and rules' },
    { testid: 'password-strength-label',type: 'span',   desc: 'Strength level text' },
    { testid: 'password-rules',         type: 'ul',     desc: 'List of 4 password rules with pass/fail indicators' },
    { testid: 'rule-length',            type: 'li',     desc: 'Min 8 chars rule (has check icon when met)' },
    { testid: 'rule-upper',             type: 'li',     desc: 'Uppercase rule' },
    { testid: 'rule-number',            type: 'li',     desc: 'Number rule' },
    { testid: 'rule-special',           type: 'li',     desc: 'Special character rule' },
    { testid: 'input-confirm',          type: 'input',  desc: 'Confirm password with live mismatch indicator' },
    { testid: 'match-indicator',        type: 'div',    desc: 'Shows match/mismatch text in real time' },
    { testid: 'select-account-type',    type: 'select', desc: 'Account type — selecting Business reveals extra fields' },
    { testid: 'business-fields',        type: 'div',    desc: 'Conditional business section (hidden by default)' },
    { testid: 'input-company',          type: 'input',  desc: 'Company name (only visible/required for Business)' },
    { testid: 'btn-submit',             type: 'button', desc: 'Submit form' },
    { testid: 'v-success',              type: 'div',    desc: 'Success state' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Debounced Username Availability Check', steps: ['Type "admi" in input-username','Assert username-checking is NOT yet visible (debounce pending)','Complete typing "n" (making "admin") and wait 700ms','Assert username-checking becomes visible','Wait 1500ms for API simulation to complete','Assert username-taken is visible','Clear field, type "uniqueuser99", wait 2000ms','Assert username-available is visible'] },
    { id: 'TC-02', name: 'Password Rules Checklist', steps: ['Type "abc" — assert rule-length has circle (not check)','Type "abcABCD1!" — assert all 4 rules show check icons','Assert password-strength-label shows "Strong" or "Very Strong"'] },
    { id: 'TC-03', name: 'Conditional Business Fields', steps: ['Assert business-fields is NOT visible','Select "business" from select-account-type','Assert business-fields is visible','Assert input-company is in the DOM and required','Select "personal" from select-account-type','Assert business-fields is hidden again'] },
    { id: 'TC-04', name: 'Confirm Password Live Match', steps: ['Type "Password1!" in input-password','Type "Password1!" in input-confirm','Assert match-indicator is visible and contains "match"','Clear input-confirm, type "Different!1"','Assert match-indicator contains "do not match"'] },
  ],
  pitfalls: ['Taken usernames are: admin, tester, root, alice, john','Debounce delay is 600ms + 1200ms API = wait at least 2000ms','Conditional fields change required attribute dynamically — check after select change']
},

'10-search-filter.html': {
  title: 'Search and Filter',
  difficulty: 'Intermediate',
  url: 'pages/10-search-filter.html',
  description: '20 book cards with live search (350ms debounce), multi-criteria filter panel (genre, rating, in-stock), result count badge, empty state with clear button, and grid/list view toggle.',
  elements: [
    { testid: 'search-input',               type: 'input',    desc: 'Live search box (350ms debounce)' },
    { testid: 'search-debounce-indicator',  type: 'div',      desc: 'Shown briefly during debounce' },
    { testid: 'filter-genre',               type: 'select',   desc: 'Genre filter dropdown' },
    { testid: 'filter-rating',              type: 'select',   desc: 'Minimum rating filter' },
    { testid: 'filter-available',           type: 'checkbox', desc: 'In stock only filter' },
    { testid: 'btn-clear-filters',          type: 'button',   desc: 'Clears all filters and search' },
    { testid: 'result-count',               type: 'span',     desc: 'Text: "X books found" (aria-live)' },
    { testid: 'results-grid',               type: 'div',      desc: 'Book cards container (role=list)' },
    { testid: 'empty-state',                type: 'div',      desc: 'Empty state shown when no results' },
    { testid: 'btn-empty-clear',            type: 'button',   desc: 'Clear filters from empty state' },
    { testid: 'view-grid',                  type: 'button',   desc: 'Switch to grid view (aria-pressed)' },
    { testid: 'view-list',                  type: 'button',   desc: 'Switch to list view (aria-pressed)' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Live Search', steps: ['Assert result-count shows "20 books found"','Type "dune" in search-input','Wait 400ms for debounce','Assert results-grid has exactly 1 card visible','Assert that card contains "Dune" in its title'] },
    { id: 'TC-02', name: 'Genre Filter', steps: ['Select "sci-fi" from filter-genre','Assert only sci-fi cards are shown','Assert result-count shows correct filtered number'] },
    { id: 'TC-03', name: 'Empty State', steps: ['Type "zzzzzzzzz" in search-input','Wait 400ms','Assert results-grid has no visible cards','Assert empty-state is visible','Assert result-count shows "0 books found"','Click btn-empty-clear','Assert search-input is empty','Assert result-count shows "20 books found"'] },
    { id: 'TC-04', name: 'Combined Filters', steps: ['Select "tech" genre','Select "5" from filter-rating (5 stars only)','Assert only high-rated tech books appear'] },
  ],
  pitfalls: ['Search debounce is 350ms — always wait before asserting count','result-count element has aria-live="polite" — suitable for accessibility assertions','book card test IDs are dynamic: book-card-1, book-card-2... etc']
},

'11-multi-step-form.html': {
  title: 'Multi Step Wizard Form',
  difficulty: 'Advanced',
  url: 'pages/11-multi-step-form.html',
  description: '4-step checkout wizard: Account (email + password), Profile (name + country), Plan selection (radio cards), and Review step. Progress bar, step counter, per-step validation, back/next, and state preservation.',
  elements: [
    { testid: 'wizard-progress',   type: 'div',    desc: 'Progress bar and step indicator' },
    { testid: 'step-counter',      type: 'span',   desc: 'Text showing "Step N of 4"' },
    { testid: 'step-label-1',      type: 'div',    desc: 'Step 1 label (Account)' },
    { testid: 'step-label-2',      type: 'div',    desc: 'Step 2 label (Profile)' },
    { testid: 'step-label-3',      type: 'div',    desc: 'Step 3 label (Plan)' },
    { testid: 'step-label-4',      type: 'div',    desc: 'Step 4 label (Review)' },
    { testid: 'step-1',            type: 'div',    desc: 'Step 1 container (Account details)' },
    { testid: 'step-2',            type: 'div',    desc: 'Step 2 container (Profile)' },
    { testid: 'step-3',            type: 'div',    desc: 'Step 3 container (Plan)' },
    { testid: 'step-4',            type: 'div',    desc: 'Step 4 container (Review summary)' },
    { testid: 'input-w-email',     type: 'input',  desc: 'Email input in step 1' },
    { testid: 'input-w-password',  type: 'input',  desc: 'Password input in step 1' },
    { testid: 'input-w-confirm',   type: 'input',  desc: 'Confirm password in step 1' },
    { testid: 'input-w-first',     type: 'input',  desc: 'First name in step 2' },
    { testid: 'input-w-last',      type: 'input',  desc: 'Last name in step 2' },
    { testid: 'select-w-country',  type: 'select', desc: 'Country in step 2' },
    { testid: 'radio-plan-free',   type: 'radio',  desc: 'Free plan radio ($0/mo)' },
    { testid: 'radio-plan-pro',    type: 'radio',  desc: 'Pro plan radio ($29/mo, pre-selected)' },
    { testid: 'radio-plan-enterprise', type: 'radio', desc: 'Enterprise plan radio ($99/mo)' },
    { testid: 'review-summary',    type: 'div',    desc: 'Review step summary of all entered data' },
    { testid: 'btn-wizard-next',   type: 'button', desc: 'Next / Submit button (text changes on last step)' },
    { testid: 'btn-wizard-back',   type: 'button', desc: 'Back button (hidden on step 1)' },
    { testid: 'wizard-success',    type: 'div',    desc: 'Final success state' },
    { testid: 'wizard-success-msg',type: 'p',      desc: 'Success message with username and plan' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Complete Wizard Flow', steps: ['Assert step-counter text is "Step 1 of 4"','Fill email, password, confirm in step 1','Click btn-wizard-next','Assert step-2 is visible, step-1 is hidden','Fill first name, last name, select country in step 2','Click btn-wizard-next','Select enterprise plan radio','Click btn-wizard-next','Assert step-4 is visible with review-summary','Assert review-summary shows entered email and plan','Click btn-wizard-next (Submit)','Assert wizard-success is visible','Assert wizard-success-msg contains plan name'] },
    { id: 'TC-02', name: 'Step Validation', steps: ['On step 1, click btn-wizard-next without filling any field','Assert inline errors appear for email and password','Assert step-counter still shows "Step 1 of 4" (no advance)'] },
    { id: 'TC-03', name: 'Back Navigation Preserves State', steps: ['Fill step 1 and advance to step 2','Click btn-wizard-back','Assert step-1 is visible again','Assert previously filled email is still in input-w-email (state preserved)'] },
  ],
  pitfalls: ['Step containers use display:none not hidden attribute','Review summary is built from JS state, not DOM inputs — no direct selector','btn-wizard-back is hidden (display:none) on step 1 — becomes visible from step 2 onward','Button text changes from "Next" to "Submit" on step 4']
},

'12-async-loading.html': {
  title: 'Async Loading and Spinners',
  difficulty: 'Advanced',
  url: 'pages/12-async-loading.html',
  description: 'Four async patterns: spinner + delayed content (2s), skeleton loader (2s), retry mechanism (fail twice then succeed), and sequential delayed element appearance (500ms/1500ms/3000ms).',
  elements: [
    { testid: 'btn-load-data',            type: 'button', desc: 'Triggers 2-second simulated data fetch' },
    { testid: 'loading-spinner-area',     type: 'div',    desc: 'Spinner container (display:none initially)' },
    { testid: 'loaded-content',           type: 'div',    desc: 'Content revealed after loading (display:none initially)' },
    { testid: 'async-table',              type: 'table',  desc: 'Table populated after async load' },
    { testid: 'async-table-body',         type: 'tbody',  desc: 'Table body with loaded rows' },
    { testid: 'btn-skeleton-load',        type: 'button', desc: 'Triggers skeleton loader sequence (2s)' },
    { testid: 'skeleton-container',       type: 'div',    desc: 'Skeleton placeholder cards during loading' },
    { testid: 'skeleton-content',         type: 'div',    desc: 'Real content cards after skeleton loading' },
    { testid: 'btn-retry-start',          type: 'button', desc: 'Starts the 3-attempt retry sequence' },
    { testid: 'retry-status',             type: 'div',    desc: 'Status text during retry attempts' },
    { testid: 'retry-attempt-1',          type: 'div',    desc: 'Log entry for attempt 1 (failure)' },
    { testid: 'retry-attempt-2',          type: 'div',    desc: 'Log entry for attempt 2 (failure)' },
    { testid: 'retry-attempt-3',          type: 'div',    desc: 'Log entry for attempt 3 (success)' },
    { testid: 'retry-success',            type: 'div',    desc: 'Success message after retry' },
    { testid: 'btn-start-delayed',        type: 'button', desc: 'Starts sequential element appearance' },
    { testid: 'delayed-el-1',             type: 'div',    desc: 'Appears after 500ms' },
    { testid: 'delayed-el-2',             type: 'div',    desc: 'Appears after 1500ms' },
    { testid: 'delayed-el-3',             type: 'div',    desc: 'Appears after 3000ms (the "ready" signal)' },
    { testid: 'delayed-final-btn',        type: 'button', desc: 'Button that appears after delayed-el-3' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Wait for Spinner then Content', steps: ['Assert loading-spinner-area is NOT visible','Click btn-load-data','Assert loading-spinner-area is visible','Wait for loaded-content to be visible (timeout: 5000ms)','Assert loading-spinner-area is hidden','Assert async-table-body has 5 rows'] },
    { id: 'TC-02', name: 'Skeleton Loader', steps: ['Click btn-skeleton-load','Assert skeleton-container is visible with placeholder cards','Assert skeleton-content is hidden','Wait for skeleton-content to become visible (timeout: 5000ms)','Assert skeleton-container is hidden','Assert skeleton-content has 4 cards'] },
    { id: 'TC-03', name: 'Retry Mechanism', steps: ['Click btn-retry-start','Wait for retry-attempt-1 to appear','Assert retry-attempt-1 has data-status="failure"','Wait for retry-attempt-2 to appear','Assert retry-attempt-2 data-status is "failure"','Wait for retry-attempt-3 to appear','Assert retry-attempt-3 data-status is "success"','Assert retry-success is visible'] },
    { id: 'TC-04', name: 'Sequential Element Wait', steps: ['Click btn-start-delayed','Wait for delayed-el-1 to be visible (timeout 2000ms)','Wait for delayed-el-2 to be visible (timeout 3000ms)','Wait for delayed-el-3 to be visible (timeout 5000ms)','Assert delayed-final-btn is visible','Click delayed-final-btn'] },
  ],
  pitfalls: ['NEVER use fixed sleep/timeout waits — always wait for element state changes','Retry sequence: attempt 1 at 1s, attempt 2 at 2s, attempt 3 at 3s (total 3s)','Skeleton container and content both exist in DOM — assert visibility not existence']
},

'13-drag-and-drop.html': {
  title: 'Drag and Drop',
  difficulty: 'Advanced',
  url: 'pages/13-drag-and-drop.html',
  description: 'Three drag and drop scenarios: sortable list reordering, Kanban board with 3 columns and 6 cards, and validated file-type drop zones (images only / documents only).',
  elements: [
    { testid: 'sortable-list',     type: 'div',  desc: 'Sortable list container' },
    { testid: 'sort-item-1',       type: 'div',  desc: 'Sortable item 1 (draggable)' },
    { testid: 'sort-item-2',       type: 'div',  desc: 'Sortable item 2' },
    { testid: 'sort-item-3',       type: 'div',  desc: 'Sortable item 3' },
    { testid: 'btn-read-order',    type: 'button', desc: 'Reads current list order' },
    { testid: 'sort-order-output', type: 'div',  desc: 'Output showing current order' },
    { testid: 'kanban-board',      type: 'div',  desc: 'Kanban board container' },
    { testid: 'col-todo',          type: 'div',  desc: 'To Do column container' },
    { testid: 'col-doing',         type: 'div',  desc: 'In Progress column container' },
    { testid: 'col-done',          type: 'div',  desc: 'Done column container' },
    { testid: 'zone-todo',         type: 'div',  desc: 'Drop zone for To Do column' },
    { testid: 'zone-doing',        type: 'div',  desc: 'Drop zone for In Progress column' },
    { testid: 'zone-done',         type: 'div',  desc: 'Drop zone for Done column' },
    { testid: 'kanban-card-1',     type: 'div',  desc: 'Kanban card "Write test plan" (draggable)' },
    { testid: 'kanban-card-2',     type: 'div',  desc: 'Kanban card "Setup CI pipeline"' },
    { testid: 'kanban-card-3',     type: 'div',  desc: 'Kanban card "Review requirements"' },
    { testid: 'kanban-card-4',     type: 'div',  desc: 'Kanban card "Implement login page" (in-progress)' },
    { testid: 'count-todo',        type: 'span', desc: 'Number of cards in To Do column' },
    { testid: 'count-doing',       type: 'span', desc: 'Number of cards in In Progress column' },
    { testid: 'count-done',        type: 'span', desc: 'Number of cards in Done column' },
    { testid: 'drop-target-1',     type: 'div',  desc: 'Zone 1 — accepts images only' },
    { testid: 'drop-target-2',     type: 'div',  desc: 'Zone 2 — accepts documents only' },
    { testid: 'chip-photo',        type: 'div',  desc: 'Draggable file chip: photo.jpg (image type)' },
    { testid: 'chip-report',       type: 'div',  desc: 'Draggable file chip: report.pdf (document type)' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Sortable List Reorder', steps: ['Use dragAndDrop to drag sort-item-3 above sort-item-1','Click btn-read-order','Assert sort-order-output shows item 3 first'] },
    { id: 'TC-02', name: 'Kanban Card Move', steps: ['Assert count-todo shows "3"','Drag kanban-card-1 to zone-done','Assert kanban-card-1 is now inside col-done','Assert count-done shows "2"','Assert count-todo shows "2"'] },
    { id: 'TC-03', name: 'Drop Zone Validation', steps: ['Drag chip-photo to drop-target-1 (images only)','Assert chip-photo appears in zone-1-contents','Drag chip-report to drop-target-1 (wrong type)','Assert dropzone-msg contains "Wrong zone"'] },
  ],
  pitfalls: ['HTML5 native DnD — use Playwright dragAndDrop() not mouse.down/move/up which may not trigger dataTransfer','Assert destination container children, not pixel position','Drop zone accepts/rejects based on data-type attribute of dragged element']
},

'14-file-upload.html': {
  title: 'File Upload',
  difficulty: 'Advanced',
  url: 'pages/14-file-upload.html',
  description: 'Dropzone with drag-and-drop and click-to-select, multi-file support, type validation (jpg/png/pdf/txt), 5MB size limit, simulated upload progress bars, and single-file image preview.',
  elements: [
    { testid: 'upload-dropzone',   type: 'div',    desc: 'Clickable drag and drop zone' },
    { testid: 'file-input',        type: 'input',  desc: 'Hidden file input (use setInputFiles)' },
    { testid: 'file-list',         type: 'div',    desc: 'Container for staged file entries' },
    { testid: 'btn-upload',        type: 'button', desc: 'Upload all staged files (simulates progress)' },
    { testid: 'btn-clear-files',   type: 'button', desc: 'Remove all staged files' },
    { testid: 'upload-success',    type: 'div',    desc: 'Success message after upload completes' },
    { testid: 'file-errors',       type: 'div',    desc: 'Shows validation errors for rejected files' },
    { testid: 'single-file-input', type: 'input',  desc: 'Single image upload with preview' },
    { testid: 'single-file-preview', type: 'div', desc: 'Preview container (shown after valid image selected)' },
    { testid: 'preview-img',       type: 'img',    desc: 'Image preview element' },
    { testid: 'single-file-error', type: 'div',    desc: 'Error for invalid single file' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Upload Valid File', steps: ['Use setInputFiles("#file-input", ["path/to/sample.pdf"])','Assert a file entry with name "sample.pdf" is in file-list','Assert btn-upload is visible','Click btn-upload','Wait for upload-success to be visible (timeout: 5000ms)','Assert progress bars all at 100%'] },
    { id: 'TC-02', name: 'Remove File', steps: ['Stage a file using setInputFiles','Assert file appears in file-list','Click btn-remove-0 (remove button for first file)','Assert file is no longer in file-list','Assert btn-upload is hidden when list is empty'] },
    { id: 'TC-03', name: 'Image Preview', steps: ['Use setInputFiles("#single-file-input", ["path/to/image.jpg"])','Assert single-file-preview is visible','Assert preview-img src attribute starts with "data:image"','Assert preview-info contains file name'] },
  ],
  pitfalls: ['File input is visually hidden — use setInputFiles(\'#file-input\', paths) directly','Type validation happens client-side — test with wrong extensions to verify rejection','Maximum 5 files — adding a 6th should trigger an error in file-errors','Upload progress is simulated with setTimeout — wait for upload-success not network']
},

'15-localstorage-state.html': {
  title: 'LocalStorage and State',
  difficulty: 'Advanced',
  url: 'pages/15-localstorage-state.html',
  description: 'Shopping cart, user preferences, and notes CRUD — all persisted to localStorage with keys qalab_cart, qalab_prefs, qalab_notes. Includes a storage inspector.',
  elements: [
    { testid: 'btn-add-playwright', type: 'button', desc: 'Add "Playwright Course" ($49) to cart' },
    { testid: 'btn-add-selenium',   type: 'button', desc: 'Add "Selenium Masterclass" ($39) to cart' },
    { testid: 'cart-count',         type: 'span',   desc: 'Number of items in cart' },
    { testid: 'cart-items',         type: 'div',    desc: 'Cart items container' },
    { testid: 'cart-total',         type: 'span',   desc: 'Cart total price text' },
    { testid: 'btn-checkout',       type: 'button', desc: 'Place order and clear cart' },
    { testid: 'btn-clear-cart',     type: 'button', desc: 'Empty the cart' },
    { testid: 'pref-language',      type: 'select', desc: 'Language preference' },
    { testid: 'pref-timezone',      type: 'select', desc: 'Timezone preference' },
    { testid: 'pref-notifications', type: 'checkbox', desc: 'Email notifications preference' },
    { testid: 'btn-save-prefs',     type: 'button', desc: 'Save preferences to localStorage' },
    { testid: 'prefs-saved-msg',    type: 'div',    desc: 'Success message after saving prefs' },
    { testid: 'note-input',         type: 'input',  desc: 'Text input for new note' },
    { testid: 'btn-add-note',       type: 'button', desc: 'Add note to list' },
    { testid: 'notes-list',         type: 'div',    desc: 'Container for all notes' },
    { testid: 'btn-inspect-storage',type: 'button', desc: 'Dumps current localStorage to storage-dump' },
    { testid: 'storage-dump',       type: 'pre',    desc: 'JSON dump of localStorage contents' },
    { testid: 'btn-nuke-storage',   type: 'button', desc: 'Clears ALL localStorage (with confirm)' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Cart Persistence Across Reload', steps: ['Clear localStorage with page.evaluate(() => localStorage.clear())','Reload page','Click btn-add-playwright','Assert cart-count is "1"','Assert cart-total text is "$49"','Reload the page','Assert cart-count is still "1" (persisted)'] },
    { id: 'TC-02', name: 'Preferences Persist', steps: ['Select "pt" (Português) from pref-language','Check pref-notifications','Click btn-save-prefs','Assert prefs-saved-msg is visible','Reload the page','Assert pref-language selected value is "pt"','Assert pref-notifications is checked'] },
    { id: 'TC-03', name: 'Notes CRUD', steps: ['Type "My test note" in note-input','Click btn-add-note','Assert notes-list has 1 entry containing "My test note"','Click btn-inspect-storage','Assert storage-dump contains "qalab_notes"','Click delete button on the note','Assert notes-list is empty'] },
  ],
  pitfalls: ['localStorage persists between test runs — always execute localStorage.clear() in test setup','Use page.evaluate() to read/write storage directly: page.evaluate(() => JSON.parse(localStorage.getItem("qalab_cart")))','Notes use timestamp IDs — assert by text content not by ID','btn-nuke-storage triggers browser confirm() dialog']
},

'16-nested-iframes.html': {
  title: 'Nested iFrames',
  difficulty: 'Expert',
  url: 'pages/16-nested-iframes.html',
  description: 'Two levels of nested same-origin iframes created via srcdoc. Each level has its own form, inputs and submit button. Requires frameLocator() chaining in Playwright.',
  elements: [
    { testid: 'outer-input',       type: 'input',   desc: 'Text input in the OUTER PAGE (no frame)' },
    { testid: 'btn-outer-submit',  type: 'button',  desc: 'Submit button in the outer page' },
    { testid: 'outer-result',      type: 'div',     desc: 'Outer page result div' },
    { testid: 'iframe-a',          type: 'iframe',  desc: 'Frame A — level 1 iframe' },
  ],
  innerElements: {
    frameA: [
      { id: 'frame-a-input',       type: 'input',  desc: 'Text input inside Frame A' },
      { id: 'btn-frame-a-submit',  type: 'button', desc: 'Submit button inside Frame A' },
      { id: 'frame-a-result',      type: 'div',    desc: 'Result div inside Frame A' },
      { id: 'iframe-b',            type: 'iframe', desc: 'Nested Frame B inside Frame A' },
    ],
    frameB: [
      { id: 'frame-b-input',       type: 'input',  desc: 'Text input inside Frame B (nested)' },
      { id: 'btn-frame-b-submit',  type: 'button', desc: 'Submit button inside Frame B' },
      { id: 'frame-b-result',      type: 'div',    desc: 'Result div inside Frame B' },
    ]
  },
  scenarios: [
    { id: 'TC-01', name: 'Outer Page Interaction', steps: ['Fill outer-input with "Outer value"','Click btn-outer-submit','Assert outer-result is visible and contains "Outer value"'] },
    { id: 'TC-02', name: 'Frame A Interaction', steps: ['Get frameLocator("#iframe-a")','Fill #frame-a-input with "Frame A data"','Click #btn-frame-a-submit','Assert #frame-a-result contains "Frame A data"'] },
    { id: 'TC-03', name: 'Nested Frame B Interaction', steps: ['Chain: frameLocator("#iframe-a").frameLocator("#iframe-b")','Fill #frame-b-input with "Deep nested!"','Click #btn-frame-b-submit','Assert #frame-b-result contains "Deep nested!"'] },
  ],
  pitfalls: ['Regular page.locator() will NOT find elements inside iframes — always use frameLocator()','In Selenium: driver.switchTo().frame("frame-a") then switch again for frame-b; always switch back to default','Iframes built with srcdoc — same-origin, no CORS issues','Always switch back to default content after working in a frame (Selenium)']
},

'17-shadow-dom.html': {
  title: 'Shadow DOM',
  difficulty: 'Expert',
  url: 'pages/17-shadow-dom.html',
  description: 'Three custom Web Components with open shadow roots: qa-card (3 instances), qa-login (shadow form), and nested qa-outer > qa-inner (double shadow pierce required).',
  elements: [
    { testid: 'qa-card-1',         type: 'custom-element', desc: 'Shadow card 1 — "Login Component"' },
    { testid: 'qa-card-2',         type: 'custom-element', desc: 'Shadow card 2 — "Data Table Widget"' },
    { testid: 'qa-card-3',         type: 'custom-element', desc: 'Shadow card 3 — "Notification Bell"' },
    { testid: 'card-event-log',    type: 'div',    desc: 'Shows event fired when shadow card button is clicked' },
    { testid: 'shadow-login',      type: 'custom-element', desc: 'qa-login host element' },
    { testid: 'shadow-login-result',type: 'div',   desc: 'Result shown in outer page after shadow login' },
    { testid: 'shadow-nested',     type: 'custom-element', desc: 'qa-outer host (contains qa-inner with nested shadow)' },
  ],
  innerElements: {
    shadowCard: [
      { testid: 'shadow-card-title',  desc: 'Card title inside shadow root' },
      { testid: 'shadow-card-status', desc: 'Status badge inside shadow root' },
      { testid: 'shadow-card-btn',    desc: 'View Details button inside shadow root' },
    ],
    shadowLogin: [
      { testid: 'shadow-input-email',    desc: 'Email input inside shadow root' },
      { testid: 'shadow-input-password', desc: 'Password input inside shadow root' },
      { testid: 'shadow-btn-submit',     desc: 'Submit button inside shadow root' },
    ],
    nestedShadow: [
      { testid: 'qa-inner',   desc: 'Inner shadow host element' },
      { id:    'nested-input',  desc: 'Input inside nested shadow (level 2)' },
      { id:    'nested-btn',    desc: 'Button inside nested shadow (level 2)' },
    ]
  },
  scenarios: [
    { id: 'TC-01', name: 'Click Shadow Card Button', steps: ['Locate card host: page.locator("[data-testid=\'qa-card-1\']")','Pierce shadow to find the button: locator("[data-testid=\'shadow-card-btn\']")','Click the button','Assert card-event-log in the outer page contains "Login Component"'] },
    { id: 'TC-02', name: 'Shadow Login Form', steps: ['Locate shadow-login host element','Pierce to find shadow-input-email and fill "test@test.com"','Pierce to find shadow-input-password and fill "pass123"','Click shadow-btn-submit','Assert shadow-login-result in outer page is visible'] },
    { id: 'TC-03', name: 'Nested Shadow (Double Pierce)', steps: ['Locate qa-outer host','Pierce into outer shadow to find qa-inner','Pierce into inner shadow to find #nested-input','Fill nested-input with "Deeply nested value"','Click nested-btn','Assert #nested-result text contains the value'] },
  ],
  pitfalls: ['Playwright auto-pierces OPEN shadow roots — standard locator() works across shadow boundaries','Closed shadow roots (mode:"closed") are inaccessible from outside — these are all open','In Selenium: use host.shadowRoot.querySelector() via execute_script','Custom events have bubbles:true composed:true — they cross shadow boundaries to the outer document']
},

'18-race-conditions.html': {
  title: 'Race Conditions and Flakiness',
  difficulty: 'Expert',
  url: 'pages/18-race-conditions.html',
  description: 'Five intentional timing challenges: disappearing button (2s window), randomized delay (1-5s), auto-refreshing stale table (every 3s), dynamic IDs anti-pattern, CSS-hidden vs display:none.',
  elements: [
    { testid: 'btn-start-disappear',       type: 'button', desc: 'Starts the 2-second disappearing button window' },
    { testid: 'btn-fleeting',              type: 'button', desc: 'Button visible for only 2 seconds — must be clicked in time' },
    { testid: 'countdown-display',         type: 'div',    desc: 'Shows remaining time for fleeting button' },
    { testid: 'disappear-result',          type: 'div',    desc: 'Shows success or failure after window closes' },
    { testid: 'btn-random-delay',          type: 'button', desc: 'Triggers fetch with 1-5 second random delay' },
    { testid: 'random-delay-spinner',      type: 'div',    desc: 'Loading spinner during random delay' },
    { testid: 'random-delay-result',       type: 'div',    desc: 'Result shown after random delay completes' },
    { testid: 'random-delay-message',      type: 'p',      desc: 'Shows actual delay time and random value' },
    { testid: 'stale-table',               type: 'table',  desc: 'Table that re-renders every 3 seconds' },
    { testid: 'stale-countdown',           type: 'span',   desc: 'Countdown to next table re-render' },
    { testid: 'btn-stale-toggle',          type: 'button', desc: 'Pause/resume the auto re-render' },
    { testid: 'btn-regenerate-ids',        type: 'button', desc: 'Regenerates elements with new random IDs' },
    { testid: 'dynamic-item-A',            type: 'button', desc: 'Stable testid (id attribute changes each render)' },
    { testid: 'dynamic-item-B',            type: 'button', desc: 'Stable testid (id attribute changes each render)' },
    { testid: 'css-hidden-el',             type: 'div',    desc: 'Element hidden via opacity:0 (still in layout)' },
    { testid: 'display-none-el',           type: 'div',    desc: 'Element hidden via display:none (not in layout)' },
    { testid: 'btn-toggle-visibility',     type: 'button', desc: 'Toggles both hidden elements' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Catch the Fleeting Button', steps: ['Click btn-start-disappear','Wait for btn-fleeting to be visible (timeout: 3000ms)','Click btn-fleeting immediately when visible','Assert disappear-result is visible and contains "Success"'] },
    { id: 'TC-02', name: 'Wait for Random Delay', steps: ['Click btn-random-delay','Wait for random-delay-result to be visible (timeout: 10000ms — must handle up to 5s)','Assert random-delay-message shows elapsed time','Note: NEVER use fixed sleep here'] },
    { id: 'TC-03', name: 'Stale Element Handling', steps: ['Pause auto-render with btn-stale-toggle','Read a value from stale-tbody row 1','Resume auto-render','Wait 4 seconds (re-render occurs)','Assert that the DOM row has been replaced — cached locator is now stale','Re-query the locator and read value again'] },
    { id: 'TC-04', name: 'Dynamic ID Anti-Pattern', steps: ['Read id attribute of dynamic-item-A element','Click btn-regenerate-ids','Assert id attribute has CHANGED','Assert data-testid="dynamic-item-A" still WORKS as locator (stable)','This demonstrates why id-based locators are fragile'] },
    { id: 'TC-05', name: 'CSS-Hidden vs Display None', steps: ['Assert css-hidden-el has class "invisible"','Assert css-hidden-el is in the DOM (locator.count() > 0)','Use isVisible() — assert false (opacity 0 = not visible)','Assert display-none-el is NOT visible','Click btn-toggle-visibility','Assert css-hidden-el is NOW visible (opacity revealed)','Assert display-none-el is NOW visible'] },
  ],
  pitfalls: ['Never use fixed page.waitForTimeout() — always wait for element state','Dynamic IDs change on every render — NEVER use id selectors for test automation','CSS hidden (opacity:0) element is in the DOM and in layout — isVisible() returns false but count() > 0','Stale element: after re-render, even though selector is same, element reference is invalid']
},

'19-canvas-interactions.html': {
  title: 'Canvas Interactions',
  difficulty: 'Expert',
  url: 'pages/19-canvas-interactions.html',
  description: 'HTML5 canvas drawing pad with color picker and brush size, and a clickable zones canvas with 4 named zones (Zone A-D) each 150x200px.',
  elements: [
    { testid: 'drawing-canvas', type: 'canvas', desc: 'Drawing canvas (600x300px)' },
    { testid: 'color-black',    type: 'button', desc: 'Set brush color to black' },
    { testid: 'color-red',      type: 'button', desc: 'Set brush color to red' },
    { testid: 'color-blue',     type: 'button', desc: 'Set brush color to blue' },
    { testid: 'brush-size',     type: 'input',  desc: 'Range slider for brush size (2-20)' },
    { testid: 'btn-clear-canvas',type: 'button',desc: 'Clear canvas to white' },
    { testid: 'canvas-coords',  type: 'div',    desc: 'Shows x,y coordinates at mouse position' },
    { testid: 'canvas-pixel-info', type: 'div', desc: 'Shows rgba pixel color at cursor' },
    { testid: 'canvas-stroke-count', type: 'div', desc: 'Count of drawing strokes made' },
    { testid: 'zones-canvas',   type: 'canvas', desc: 'Clickable zones canvas (600x200px)' },
    { testid: 'zone-result',    type: 'div',    desc: 'Shows which zone was clicked (aria-live)' },
    { testid: 'zone-click-count', type: 'div',  desc: 'Total number of zone clicks' },
  ],
  zoneMap: [
    { label: 'Zone A', x: 0,   y: 0, w: 150, h: 200, centerX: 75,  centerY: 100 },
    { label: 'Zone B', x: 150, y: 0, w: 150, h: 200, centerX: 225, centerY: 100 },
    { label: 'Zone C', x: 300, y: 0, w: 150, h: 200, centerX: 375, centerY: 100 },
    { label: 'Zone D', x: 450, y: 0, w: 150, h: 200, centerX: 525, centerY: 100 },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Draw a Line', steps: ['Get bounding box of #drawing-canvas','Move mouse to canvas at position { x: 50, y: 50 }','Press mouse button down','Move mouse to { x: 200, y: 150 }','Release mouse button','Assert canvas-stroke-count text contains "1"'] },
    { id: 'TC-02', name: 'Click Zone A', steps: ['Click zones-canvas at position { x: 75, y: 100 } (Zone A center)','Assert zone-result text contains "Zone A"','Assert zone-click-count shows "1"'] },
    { id: 'TC-03', name: 'Click All Zones', steps: ['Click at { x: 75, y: 100 } — assert "Zone A"','Click at { x: 225, y: 100 } — assert "Zone B"','Click at { x: 375, y: 100 } — assert "Zone C"','Click at { x: 525, y: 100 } — assert "Zone D"','Assert zone-click-count shows "4"'] },
    { id: 'TC-04', name: 'Change Color and Verify', steps: ['Click color-red button','Use page.evaluate() to read canvas pixel BEFORE drawing','Draw a stroke','Use page.evaluate() to read pixel at drawn coordinates','Assert rgba values correspond to red (r > 200, g < 50, b < 50)'] },
  ],
  pitfalls: ['Canvas has NO text selectors — all interaction is coordinate-based','Always get fresh boundingBox() before interacting — canvas position changes with window size','Pixel reading via getImageData requires HTTP server (not file://) due to CORS','Canvas drawing uses mouse events: mousemove + mousedown + mouseup chain']
},

'20-accessibility.html': {
  title: 'Accessibility Testing',
  difficulty: 'Expert',
  url: 'pages/20-accessibility.html',
  description: 'Complete accessibility practice: ARIA roles and states, live regions (polite/assertive), focus management, focus trap in modal, tab order with tabindex, skip link, and getByRole queries.',
  elements: [
    { testid: 'skip-link',           type: 'a',      desc: 'Skip to main content link (visible on focus)' },
    { testid: 'secondary-nav',       type: 'nav',    desc: 'Secondary navigation (role=navigation, aria-label)' },
    { testid: 'btn-expand',          type: 'button', desc: 'Toggle aria-expanded and reveals expandable-region' },
    { testid: 'expandable-region',   type: 'div',    desc: 'Region that toggles visibility' },
    { testid: 'expanded-text',       type: 'span',   desc: 'Text content inside expandable region' },
    { testid: 'btn-toggle-aria',     type: 'button', desc: 'Toggle button with aria-pressed state' },
    { testid: 'btn-tooltip',         type: 'button', desc: 'Button with aria-describedby tooltip' },
    { testid: 'tooltip-content',     type: 'div',    desc: 'Tooltip (role=tooltip, shown on hover/focus)' },
    { testid: 'btn-polite-announce', type: 'button', desc: 'Triggers update in polite live region' },
    { testid: 'btn-assertive-announce', type: 'button', desc: 'Triggers assertive alert' },
    { testid: 'live-polite',         type: 'div',    desc: 'Polite live region (aria-live="polite")' },
    { testid: 'live-assertive',      type: 'div',    desc: 'Assertive alert region (role=alert)' },
    { testid: 'live-status',         type: 'div',    desc: 'Status region (role=status)' },
    { testid: 'tab-input-1',         type: 'input',  desc: 'Tab index 1 — first in tab order' },
    { testid: 'tab-input-2',         type: 'input',  desc: 'Tab index 2 — second in tab order (appears third in DOM)' },
    { testid: 'tab-input-3',         type: 'input',  desc: 'Tab index 3 — third in tab order (appears second in DOM)' },
    { testid: 'btn-open-focus-trap', type: 'button', desc: 'Opens the focus trap modal' },
    { testid: 'modal-focus-trap',    type: 'div',    desc: 'Modal dialog with focus trap' },
    { testid: 'trap-input-1',        type: 'input',  desc: 'First focusable element inside focus trap' },
    { testid: 'trap-input-2',        type: 'input',  desc: 'Second focusable in focus trap' },
    { testid: 'btn-trap-confirm',    type: 'button', desc: 'Confirm button inside focus trap' },
    { testid: 'article-content',     type: 'article', desc: 'Article element (role=article, aria-label)' },
    { testid: 'article-title',       type: 'h2',     desc: 'Article heading' },
  ],
  scenarios: [
    { id: 'TC-01', name: 'Expand Toggle and ARIA States', steps: ['Use getByRole("button", { name: "Toggle Details" })','Assert aria-expanded attribute is "false"','Click the button','Assert aria-expanded is "true"','Assert expandable-region is visible','Assert expanded-text is visible'] },
    { id: 'TC-02', name: 'Pressed Toggle State', steps: ['Assert btn-toggle-aria has aria-pressed="false"','Click btn-toggle-aria','Assert aria-pressed is "true"','Assert button text changes to indicate active state'] },
    { id: 'TC-03', name: 'Live Region Update', steps: ['Assert live-polite initial text','Click btn-polite-announce','Assert live-polite text has updated (contains announcement)','Click btn-assertive-announce','Assert live-assertive is visible and contains alert text'] },
    { id: 'TC-04', name: 'Focus Trap', steps: ['Click btn-open-focus-trap','Assert modal-focus-trap is visible','Assert focus is on trap-input-1','Press Tab — focus should move to trap-input-2','Press Tab — focus should move to btn-trap-confirm','Press Tab — focus should wrap back to trap-input-1 (trapped)','Press Escape — assert modal closes'] },
    { id: 'TC-05', name: 'Role-Based Queries', steps: ['getByRole("heading", { name: /The Importance/ })', 'getByRole("article") — should find article-content','getByRole("navigation", { name: "Secondary navigation" })','getByRole("status") — should find live-status region'] },
  ],
  pitfalls: ['Live regions update asynchronously — wait for text content change not element visibility','Focus trap uses keyboard Tab events — simulate with page.keyboard.press("Tab")','Skip link is only visible on focus — use page.keyboard.press("Tab") first then assert visibility','getByRole is the gold standard for accessibility assertion — prefer it over getByTestId in A11y tests']
},

};

